<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Wallet/Wallet.Domain/Wallet.Domain.csproj" />
    <ProjectReference Include="../P2P.Domain/P2P.Domain.csproj" />
  </ItemGroup>
</Project>
