<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RegulatoryReporting.Application\RegulatoryReporting.Application.csproj" />
    <ProjectReference Include="..\RegulatoryReporting.Contracts\RegulatoryReporting.Contracts.csproj" />
  </ItemGroup>
</Project>
