<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentIntent.Domain\PaymentIntent.Domain.csproj" />
    <ProjectReference Include="..\PaymentIntent.Application\PaymentIntent.Application.csproj" />
    <ProjectReference Include="..\PaymentIntent.Contracts\PaymentIntent.Contracts.csproj" />
    <ProjectReference Include="..\PaymentIntent.Infrastructure\PaymentIntent.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
