<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MobileMoney.Domain\MobileMoney.Domain.csproj" />
    <ProjectReference Include="..\MobileMoney.Application\MobileMoney.Application.csproj" />
  </ItemGroup>

</Project>