<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Reconciliation.Application/Reconciliation.Application.csproj" />
    <ProjectReference Include="../../Transfer/Transfer.Application/Transfer.Application.csproj" />
    <ProjectReference Include="../../Wallet/Wallet.Application/Wallet.Application.csproj" />
    <ProjectReference Include="../../Wallet/Wallet.Domain/Wallet.Domain.csproj" />
  </ItemGroup>
</Project>
