using AfriWallet.Fraud.DeviceRisk.Application.Abstractions;using AfriWallet.Fraud.DeviceRisk.Application.Policies;using AfriWallet.Fraud.DeviceRisk.Domain.Models;using AfriWallet.Fraud.DeviceRisk.Domain.Signals;
namespace AfriWallet.Fraud.DeviceRisk.Application.Services;
public sealed class DeviceAccountRiskService(IFraudSignalReader reader,IDeviceRiskRepository repository,IDeviceRiskAuditStore audit,IDeviceRiskClock clock,DeviceRiskPolicy policy)
{
    public async Task<DeviceRiskResult> CalculateAsync(CalculateDeviceRiskCommand command,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(command.Awid)||string.IsNullOrWhiteSpace(command.DeviceId)||string.IsNullOrWhiteSpace(command.Actor))throw new ArgumentException("AWID, DeviceId and Actor are required.");var from=clock.UtcNow.AddHours(-24);var account=await reader.GetBySubjectAsync("AWID",command.Awid,from,ct);var device=await reader.GetBySubjectAsync("DEVICE",command.DeviceId,from,ct);var signals=account.Concat(device).GroupBy(x=>x.EventId,StringComparer.OrdinalIgnoreCase).Select(x=>x.First()).OrderBy(x=>x.OccurredAt).ToArray();var factors=new List<DeviceRiskFactor>();AddSingle(signals,factors,"NewDevice",DeviceRiskFactorType.NewDevice,20,"new device signal");AddSingle(signals,factors,"DeviceChanged",DeviceRiskFactorType.DeviceChanged,25,"device changed signal");AddCount(signals,factors,"LoginFailed",DeviceRiskFactorType.LoginFailures,3,15,30,"failed login signals");AddCount(signals,factors,"PinFailure",DeviceRiskFactorType.PinFailures,3,15,30,"PIN failure signals");AddMultipleDevices(signals,factors);AddLoginVelocityFactor(signals,factors);AddAttribute(signals,factors,"sessionAnomaly",DeviceRiskFactorType.SessionAnomaly,25,"session anomaly signal present");AddMismatch(signals,factors,command.DeviceId);var score=Math.Clamp(factors.Sum(x=>x.Score),0,100);var profile=new DeviceAccountRiskProfile(Guid.NewGuid(),command.Awid,command.DeviceId,score,policy.ResolveBand(score),policy.ResolveRecommendation(score),factors,clock.UtcNow);await repository.SaveAsync(profile,ct);await audit.AppendAsync(new DeviceRiskAuditEvent(Guid.NewGuid(),profile.Awid,profile.DeviceId,profile.ProfileId,"device.risk.calculated",command.Actor,clock.UtcNow,new Dictionary<string,string>{{"score",score.ToString()},{"band",profile.Band.ToString()},{"recommendation",profile.Recommendation.ToString()}}),ct);return new(profile.ProfileId,profile.Awid,profile.DeviceId,profile.Score,profile.Band,profile.Recommendation,profile.Factors,profile.CalculatedAtUtc);}
    private static void AddSingle(IEnumerable<FraudSignalSnapshot>s,ICollection<DeviceRiskFactor>f,string type,DeviceRiskFactorType factor,int score,string reason){var x=s.LastOrDefault(x=>string.Equals(x.Type,type,StringComparison.OrdinalIgnoreCase));if(x is not null)f.Add(new(factor,score,reason,x.EventId));}
    private static void AddCount(IEnumerable<FraudSignalSnapshot>s,ICollection<DeviceRiskFactor>f,string type,DeviceRiskFactorType factor,int threshold,int low,int high,string reason){var list=s.Where(x=>string.Equals(x.Type,type,StringComparison.OrdinalIgnoreCase)).ToArray();if(list.Length>=threshold)f.Add(new(factor,list.Length>=5?high:low,$"{list.Length} {reason}",list[^1].EventId));}
    private static void AddMultipleDevices(IEnumerable<FraudSignalSnapshot>s,ICollection<DeviceRiskFactor>f){var ids=s.Select(x=>x.Attributes.TryGetValue("deviceId",out var id)?id:null).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.Ordinal).ToArray();if(ids.Length>=3)f.Add(new(DeviceRiskFactorType.MultipleDevices,ids.Length>=5?30:20,$"{ids.Length} devices associated",null));}
    private static void AddLoginVelocityFactor(IReadOnlyCollection<FraudSignalSnapshot>s,ICollection<DeviceRiskFactor>f){var events=s.Where(x=>string.Equals(x.Type,"LoginFailed",StringComparison.OrdinalIgnoreCase)).OrderBy(x=>x.OccurredAt).ToArray();for(var i=0;i<=events.Length-5;i++)if(events[i+4].OccurredAt-events[i].OccurredAt<=TimeSpan.FromMinutes(10)){f.Add(new(DeviceRiskFactorType.LoginVelocity,25,"5+ failed logins within 10 minutes",null));break;}}
    private static void AddAttribute(IEnumerable<FraudSignalSnapshot>s,ICollection<DeviceRiskFactor>f,string key,DeviceRiskFactorType type,int score,string reason){var x=s.LastOrDefault(x=>x.Attributes.TryGetValue(key,out var value)&&string.Equals(value,"true",StringComparison.OrdinalIgnoreCase));if(x is not null)f.Add(new(type,score,reason,x.EventId));}
    private static void AddMismatch(IEnumerable<FraudSignalSnapshot>s,ICollection<DeviceRiskFactor>f,string deviceId){var x=s.LastOrDefault(x=>x.Attributes.TryGetValue("deviceId",out var id)&&!string.Equals(id,deviceId,StringComparison.Ordinal));if(x is not null)f.Add(new(DeviceRiskFactorType.AccountDeviceMismatch,20,"account signal references another device",x.EventId));}
}