<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ComplianceProfile.Application\ComplianceProfile.Application.csproj" />
    <ProjectReference Include="..\ComplianceProfile.Infrastructure\ComplianceProfile.Infrastructure.csproj" />
  </ItemGroup>
</Project>
