<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PaymentRouting.Domain\PaymentRouting.Domain.csproj" />
    <ProjectReference Include="..\PaymentRouting.Application\PaymentRouting.Application.csproj" />
    <ProjectReference Include="..\PaymentRouting.Contracts\PaymentRouting.Contracts.csproj" />
    <ProjectReference Include="..\PaymentRouting.Infrastructure\PaymentRouting.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
