<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/IdentityService/IdentityService.Api/IdentityService.Api.csproj" />
    <ProjectReference Include="../../src/PaymentRequests/PaymentRequests.Application/PaymentRequests.Application.csproj" />
    <ProjectReference Include="../../src/PaymentRequests/PaymentRequests.Persistence/PaymentRequests.Persistence.csproj" />
    <ProjectReference Include="../../src/Wallet/Wallet.Application/Wallet.Application.csproj" />
    <ProjectReference Include="../../src/Wallet/Wallet.Domain/Wallet.Domain.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.11" />
  </ItemGroup>
</Project>
