<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\BankingPlatform\BeneficiaryRegistry\BeneficiaryRegistry.Domain\BeneficiaryRegistry.Domain.csproj" />
    <ProjectReference Include="..\..\src\BankingPlatform\BeneficiaryRegistry\BeneficiaryRegistry.Application\BeneficiaryRegistry.Application.csproj" />
    <ProjectReference Include="..\..\src\BankingPlatform\BeneficiaryRegistry\BeneficiaryRegistry.Infrastructure\BeneficiaryRegistry.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
