using AfriWallet.Merchants.Settlement.Domain.Compensation;
namespace AfriWallet.Merchants.Settlement.Domain.Settlements;
public sealed class MerchantSettlementOrchestration
{
 private readonly List<MerchantSettlementAttempt> _attempts=new();private readonly List<MerchantSettlementCompensation> _compensations=new();
 public MerchantSettlementOrchestration(Guid id,Guid decisionId,Guid intentId,string merchantId,MerchantSettlementRoute route,long amount,string currency,string key,DateTimeOffset now){if(id==Guid.Empty||decisionId==Guid.Empty||intentId==Guid.Empty)throw new ArgumentException("Settlement, decision and intent ids are required.");if(string.IsNullOrWhiteSpace(merchantId)||string.IsNullOrWhiteSpace(key))throw new ArgumentException("Merchant id and idempotency key are required.");if(amount<=0)throw new ArgumentOutOfRangeException(nameof(amount));if(string.IsNullOrWhiteSpace(currency)||currency.Trim().Length!=3)throw new ArgumentException("Currency must be ISO-4217 style.");SettlementId=id;PaymentDecisionId=decisionId;PaymentIntentId=intentId;MerchantId=merchantId.Trim();Route=route;AmountMinor=amount;Currency=currency.Trim().ToUpperInvariant();IdempotencyKey=key.Trim();Status=MerchantSettlementStatus.Created;ReasonCode=route==MerchantSettlementRoute.MerchantSettlement?MerchantSettlementReasonCode.SettlementRouteSelected:MerchantSettlementReasonCode.PayoutRouteSelected;CreatedAtUtc=now;UpdatedAtUtc=now;}
 public Guid SettlementId{get;}public Guid PaymentDecisionId{get;}public Guid PaymentIntentId{get;}public string MerchantId{get;}public MerchantSettlementRoute Route{get;}public long AmountMinor{get;}public string Currency{get;}public string IdempotencyKey{get;}public MerchantSettlementStatus Status{get;private set;}public MerchantSettlementReasonCode ReasonCode{get;private set;}public string? CorrelationId{get;private set;}public string? ProviderReference{get;private set;}public int AttemptCount=>_attempts.Count;public DateTimeOffset CreatedAtUtc{get;}public DateTimeOffset UpdatedAtUtc{get;private set;}public DateTimeOffset? CompletedAtUtc{get;private set;}public IReadOnlyCollection<MerchantSettlementAttempt> Attempts=>_attempts.AsReadOnly();public IReadOnlyCollection<MerchantSettlementCompensation> Compensations=>_compensations.AsReadOnly();
 public void MarkDispatchPending(string correlation,DateTimeOffset now){EnsureMutable();if(Status is not(MerchantSettlementStatus.Created or MerchantSettlementStatus.RetryPending))throw new InvalidOperationException("Settlement must be created or pending retry to dispatch.");if(string.IsNullOrWhiteSpace(correlation))throw new ArgumentException("Correlation id is required.");CorrelationId=correlation.Trim();Status=MerchantSettlementStatus.DispatchPending;UpdatedAtUtc=now;}
 public void RecordAttempt(string? reference,string result,DateTimeOffset now){EnsureMutable();if(Status!=MerchantSettlementStatus.DispatchPending)throw new InvalidOperationException("Settlement must be dispatch-pending to record an attempt.");_attempts.Add(new(Guid.NewGuid(),_attempts.Count+1,CorrelationId??throw new InvalidOperationException("Correlation id missing."),reference,result,now));ProviderReference=reference??ProviderReference;Status=MerchantSettlementStatus.Dispatched;UpdatedAtUtc=now;}
 public void Acknowledge(string? reference,DateTimeOffset now){EnsureMutable();if(Status!=MerchantSettlementStatus.Dispatched)throw new InvalidOperationException("Settlement must be dispatched before acknowledgement.");ProviderReference=reference??ProviderReference;Status=MerchantSettlementStatus.Acknowledged;ReasonCode=MerchantSettlementReasonCode.ProviderAcknowledged;UpdatedAtUtc=now;}
 public void ScheduleRetry(MerchantSettlementReasonCode reason,DateTimeOffset now){EnsureMutable();if(Status!=MerchantSettlementStatus.Dispatched)throw new InvalidOperationException("Settlement must be dispatched before scheduling retry.");Status=MerchantSettlementStatus.RetryPending;ReasonCode=reason;UpdatedAtUtc=now;}
 public void RequireCompensation(string reason,string? reference,DateTimeOffset now){EnsureMutable();if(Status!=MerchantSettlementStatus.Dispatched)throw new InvalidOperationException("Settlement must be dispatched before compensation.");if(string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Compensation reason is required.");ProviderReference=reference??ProviderReference;_compensations.Add(new(Guid.NewGuid(),reason.Trim(),reference,now,null));Status=MerchantSettlementStatus.CompensationRequired;ReasonCode=MerchantSettlementReasonCode.CompensationRequired;UpdatedAtUtc=now;}
 public void CompleteCompensation(DateTimeOffset now){if(Status!=MerchantSettlementStatus.CompensationRequired)throw new InvalidOperationException("Compensation is not required.");var last=_compensations.LastOrDefault()??throw new InvalidOperationException("Compensation record missing.");var index=_compensations.FindIndex(x=>x.CompensationId==last.CompensationId);_compensations[index]=last with{CompletedAtUtc=now};Status=MerchantSettlementStatus.Compensated;ReasonCode=MerchantSettlementReasonCode.CompensationCompleted;UpdatedAtUtc=now;}
 public void RequireManualIntervention(MerchantSettlementReasonCode reason,DateTimeOffset now){EnsureMutable();Status=MerchantSettlementStatus.ManualInterventionRequired;ReasonCode=reason;UpdatedAtUtc=now;}public void Fail(MerchantSettlementReasonCode reason,DateTimeOffset now){EnsureMutable();Status=MerchantSettlementStatus.Failed;ReasonCode=reason;UpdatedAtUtc=now;}public void Complete(DateTimeOffset now){EnsureMutable();if(Status is not(MerchantSettlementStatus.Acknowledged or MerchantSettlementStatus.Compensated))throw new InvalidOperationException("Settlement cannot complete from current state.");Status=MerchantSettlementStatus.Completed;ReasonCode=MerchantSettlementReasonCode.ProviderCompleted;CompletedAtUtc=now;UpdatedAtUtc=now;}private void EnsureMutable(){if(Status is MerchantSettlementStatus.Completed or MerchantSettlementStatus.Failed or MerchantSettlementStatus.ManualInterventionRequired)throw new InvalidOperationException("Terminal settlement state is immutable.");}
}
