<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Ledger/Ledger.Application/Ledger.Application.csproj" />
    <ProjectReference Include="../../Ledger/Ledger.Domain/Ledger.Domain.csproj" />
  </ItemGroup>
</Project>
