<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankProviderIntegration.Domain\BankProviderIntegration.Domain.csproj" />
    <ProjectReference Include="..\BankProviderIntegration.Application\BankProviderIntegration.Application.csproj" />
    <ProjectReference Include="..\BankProviderIntegration.Infrastructure\BankProviderIntegration.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
