<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FraudDecision.Domain\FraudDecision.Domain.csproj" />
    <ProjectReference Include="..\FraudDecision.Application\FraudDecision.Application.csproj" />
  </ItemGroup>
</Project>