<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RiskScoring.Application\RiskScoring.Application.csproj" />
    <ProjectReference Include="..\RiskScoring.Infrastructure\RiskScoring.Infrastructure.csproj" />
  </ItemGroup>
</Project>