using AfriWallet.Merchants.PaymentDecision.Application.Abstractions;
using AfriWallet.Merchants.PaymentDecision.Application.Commands;
using AfriWallet.Merchants.PaymentDecision.Application.Policies;
using AfriWallet.Merchants.PaymentDecision.Application.Results;
using AfriWallet.Merchants.PaymentDecision.Domain.Decisions;
namespace AfriWallet.Merchants.PaymentDecision.Application.Services;
public sealed class MerchantPaymentDecisionService(IMerchantPaymentDecisionRepository repository, IPaymentIntentDecisionReader intents, IMerchantPaymentDecisionAuditStore audit, IMerchantPaymentDecisionClock clock, MerchantPaymentAuthorizationPolicy policy)
{
 public async Task<MerchantPaymentDecisionResult> EvaluateAsync(EvaluatePaymentAuthorizationCommand c,CancellationToken ct=default){var active=await repository.GetActiveByPaymentIntentAsync(c.PaymentIntentId,ct);if(active is not null)return Map(active);return await Create(c.PaymentIntentId,c.Actor,"payment.decision.evaluated",ct);}
 public async Task<MerchantPaymentDecisionResult> ReevaluateAsync(ReevaluatePaymentAuthorizationCommand c,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(c.Reason))throw new ArgumentException("Reevaluation reason is required.",nameof(c));var active=await repository.GetActiveByPaymentIntentAsync(c.PaymentIntentId,ct);if(active is not null){active.Supersede(clock.UtcNow);await repository.SaveAsync(active,ct);await Audit(active,"payment.decision.superseded",c.Actor,ct);}return await Create(c.PaymentIntentId,c.Actor,"payment.decision.reevaluated",ct);}
 public async Task<MerchantPaymentDecisionResult> CompleteStepUpAsync(CompletePaymentStepUpCommand c,CancellationToken ct=default){var d=await Required(c.DecisionId,ct);d.CompleteStepUp(clock.UtcNow);await repository.SaveAsync(d,ct);await Audit(d,"payment.decision.step_up_completed",c.Actor,ct);return Map(d);}
 public async Task<MerchantPaymentDecisionResult> MarkCaptureEligibleAsync(MarkCaptureEligibleCommand c,CancellationToken ct=default){var d=await Required(c.DecisionId,ct);d.MarkCaptureEligible(clock.UtcNow);await repository.SaveAsync(d,ct);await Audit(d,"payment.decision.capture_eligible",c.Actor,ct);return Map(d);}
 public async Task<MerchantPaymentDecisionResult> GetAsync(Guid id,CancellationToken ct=default)=>Map(await Required(id,ct));
 private async Task<MerchantPaymentDecisionResult> Create(Guid intentId,string actor,string eventType,CancellationToken ct){if(string.IsNullOrWhiteSpace(actor))throw new ArgumentException("Actor is required.",nameof(actor));var input=await intents.GetAsync(intentId,ct)??throw new KeyNotFoundException("Payment intent not found.");var evaluation=policy.Evaluate(input,clock.UtcNow);var d=new MerchantPaymentDecision(Guid.NewGuid(),input.PaymentIntentId,input.CheckoutSessionId,input.MerchantId,evaluation.DecisionType,evaluation.ReasonCode,evaluation.PolicyVersion,evaluation.Factors,clock.UtcNow);await repository.AddAsync(d,ct);await Audit(d,eventType,actor,ct);return Map(d);}
 private async Task<MerchantPaymentDecision> Required(Guid id,CancellationToken ct)=>await repository.GetAsync(id,ct)??throw new KeyNotFoundException("Merchant payment decision not found.");
 private async Task Audit(MerchantPaymentDecision d,string type,string actor,CancellationToken ct)=>await audit.AppendAsync(new MerchantPaymentDecisionAuditEvent(Guid.NewGuid(),d.DecisionId,d.PaymentIntentId,d.MerchantId,type,actor,clock.UtcNow,new Dictionary<string,string>{{"decisionType",d.DecisionType.ToString()},{"status",d.Status.ToString()},{"reasonCode",d.ReasonCode.ToString()},{"policyVersion",d.PolicyVersion.ToString()},{"authorizationExecutionPerformed","false"},{"captureExecutionPerformed","false"},{"settlementPerformed","false"},{"payoutPerformed","false"},{"moneyMovementPerformed","false"},{"ledgerMutationPerformed","false"}}),ct);
 private static MerchantPaymentDecisionResult Map(MerchantPaymentDecision d)=>new(d.DecisionId,d.PaymentIntentId,d.CheckoutSessionId,d.MerchantId,d.DecisionType,d.Status,d.ReasonCode,d.PolicyVersion.ToString(),d.Factors.Count,d.CreatedAtUtc,d.UpdatedAtUtc);
}
