<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MerchantCheckout.Application\MerchantCheckout.Application.csproj" />
    <ProjectReference Include="..\MerchantCheckout.Infrastructure\MerchantCheckout.Infrastructure.csproj" />
  </ItemGroup>
</Project>
