using AfriWallet.Merchants.Intelligence.Application.Abstractions;
using AfriWallet.Merchants.Intelligence.Application.Models;
using AfriWallet.Merchants.Intelligence.Application.Policies;
using AfriWallet.Merchants.Intelligence.Application.Services;
using AfriWallet.Merchants.Intelligence.Domain.Findings;
using AfriWallet.Merchants.Intelligence.Infrastructure;

static void Check(string name, bool ok, ref int passed) { Console.WriteLine($"{name,-58} {(ok ? "PASS" : "FAIL")}"); if (!ok) throw new InvalidOperationException(name); passed++; }
var passed = 0; var now = new DateTimeOffset(2027, 6, 7, 9, 0, 0, TimeSpan.Zero);
var source = new SandboxMerchantIntelligenceSource(); var repository = new InMemoryMerchantIntelligenceRepository(); var audit = new InMemoryMerchantIntelligenceAuditStore(); var service = new MerchantIntelligenceService(source, repository, audit, new FixedClock(now), new MerchantRiskPolicy());
MerchantProfileSnapshot Profile(string id) => new(id, "Active", "Verified", "CI", "XOF");
MerchantIntelligenceSnapshot Snapshot(string id, IReadOnlyCollection<CheckoutMetricSnapshot>? c = null, IReadOnlyCollection<PaymentDecisionMetricSnapshot>? d = null, IReadOnlyCollection<SettlementMetricSnapshot>? s = null, IReadOnlyCollection<DisputeMetricSnapshot>? x = null) => new(id, Profile(id), c ?? [], d ?? [], s ?? [], x ?? []);

source.Set(Snapshot("AFM-CLEAN")); var clean = await service.EvaluateAsync(new("AFM-CLEAN", "scenario"));
Check("clean score zero", clean.Score == 0, ref passed); Check("clean informational", clean.Severity == MerchantRiskSeverity.Informational, ref passed); Check("clean no action", clean.Recommendation == MerchantProtectionRecommendation.NoAction, ref passed); Check("clean no patterns", clean.Patterns.Count == 0, ref passed); Check("clean metrics empty", clean.Metrics.CheckoutCount == 0 && clean.Metrics.DeclineRate == 0, ref passed);

var declineDecisions = new[] { new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Decline", "Declined", 20), new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Decline", "Declined", 30), new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Authorize", "Approved", 10) };
source.Set(Snapshot("AFM-DECLINE", d: declineDecisions)); var decline = await service.EvaluateAsync(new("AFM-DECLINE", "scenario"));
Check("decline pattern detected", decline.Patterns.Any(x => x.Code == "MER-INT-HIGH-DECLINE-RATE"), ref passed); Check("decline rate metric", Math.Abs(decline.Metrics.DeclineRate - 2d / 3d) < .001, ref passed); Check("decline count metric", decline.Metrics.DeclineCount == 2, ref passed); Check("decline severity low", decline.Severity == MerchantRiskSeverity.Low, ref passed); Check("decline recommendation monitor", decline.Recommendation == MerchantProtectionRecommendation.Monitor, ref passed);

var stepDecisions = new[] { new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "RequiresStepUp", "PendingStepUp", 65), new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Authorize", "Approved", 10), new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Authorize", "Approved", 20) };
source.Set(Snapshot("AFM-STEP", d: stepDecisions)); var step = await service.EvaluateAsync(new("AFM-STEP", "scenario"));
Check("step-up pattern detected", step.Patterns.Any(x => x.Code == "MER-INT-HIGH-STEP-UP-RATE"), ref passed); Check("step-up rate metric", Math.Abs(step.Metrics.StepUpRate - 1d / 3d) < .001, ref passed); Check("step-up recommendation monitor", step.Recommendation == MerchantProtectionRecommendation.Monitor, ref passed);

var criticalDecision = new[] { new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Decline", "Declined", 90) };
source.Set(Snapshot("AFM-CRITICAL-SIGNAL", d: criticalDecision)); var criticalSignal = await service.EvaluateAsync(new("AFM-CRITICAL-SIGNAL", "scenario"));
Check("critical signal pattern detected", criticalSignal.Patterns.Any(x => x.Code == "MER-INT-CRITICAL-RISK-SIGNALS"), ref passed); Check("critical signal score contribution", criticalSignal.Score == 25, ref passed);

var settlementDecisions = declineDecisions; var settlementRows = new[] { new SettlementMetricSnapshot(Guid.NewGuid(), "MerchantSettlement", "Failed", 3), new SettlementMetricSnapshot(Guid.NewGuid(), "MerchantPayout", "Completed", 1) };
source.Set(Snapshot("AFM-SETTLEMENT", d: settlementDecisions, s: settlementRows)); var settlement = await service.EvaluateAsync(new("AFM-SETTLEMENT", "scenario"));
Check("settlement failure pattern", settlement.Patterns.Any(x => x.Code == "MER-INT-SETTLEMENT-FAILURES"), ref passed); Check("settlement retry pattern", settlement.Patterns.Any(x => x.Code == "MER-INT-SETTLEMENT-RETRIES"), ref passed); Check("settlement compound pattern", settlement.Patterns.Any(x => x.Code == "MER-INT-COMPOUND-RISK"), ref passed); Check("settlement pattern count", settlement.Patterns.Count == 4, ref passed); Check("settlement recommendation", settlement.Recommendation == MerchantProtectionRecommendation.ReviewSettlementActivity, ref passed); Check("settlement severity high", settlement.Severity == MerchantRiskSeverity.High, ref passed); Check("settlement failure metric", settlement.Metrics.SettlementFailureCount == 1, ref passed); Check("settlement retry metric", settlement.Metrics.SettlementRetryCount == 2, ref passed);

var checkouts = Enumerable.Range(0, 100).Select(_ => new CheckoutMetricSnapshot(Guid.NewGuid(), "ReadyForPayment", 100, "XOF")).ToArray(); var disputes = new[] { new DisputeMetricSnapshot(Guid.NewGuid(), "ProcessingError", "RefundRecommended", "Resolved"), new DisputeMetricSnapshot(Guid.NewGuid(), "UnauthorizedTransaction", "ChargebackRecommended", "Resolved"), new DisputeMetricSnapshot(Guid.NewGuid(), "Other", "Decline", "Resolved") };
source.Set(Snapshot("AFM-DISPUTES", c: checkouts, x: disputes)); var dispute = await service.EvaluateAsync(new("AFM-DISPUTES", "scenario"));
Check("dispute concentration pattern", dispute.Patterns.Any(x => x.Code == "MER-INT-DISPUTE-CONCENTRATION"), ref passed); Check("refund chargeback pattern", dispute.Patterns.Any(x => x.Code == "MER-INT-REFUND-CHARGEBACK-CONCENTRATION"), ref passed); Check("high checkout volume pattern", dispute.Patterns.Any(x => x.Code == "MER-INT-HIGH-CHECKOUT-VOLUME"), ref passed); Check("dispute compound pattern", dispute.Patterns.Any(x => x.Code == "MER-INT-COMPOUND-RISK"), ref passed); Check("customer protection recommendation", dispute.Recommendation == MerchantProtectionRecommendation.CustomerProtectionReview, ref passed); Check("dispute metrics", dispute.Metrics.DisputeCount == 3 && dispute.Metrics.RefundRecommendationCount == 1 && dispute.Metrics.ChargebackRecommendationCount == 1, ref passed);

var allDecisions = new[] { new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Decline", "Declined", 95), new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "Decline", "Declined", 90), new PaymentDecisionMetricSnapshot(Guid.NewGuid(), "RequiresStepUp", "PendingStepUp", 70) };
source.Set(Snapshot("AFM-COMPOUND", c: checkouts, d: allDecisions, s: settlementRows, x: disputes)); var compound = await service.EvaluateAsync(new("AFM-COMPOUND", "scenario"));
Check("compound score clamps at 100", compound.Score == 100, ref passed); Check("compound severity critical", compound.Severity == MerchantRiskSeverity.Critical, ref passed); Check("compound escalates operations", compound.Recommendation == MerchantProtectionRecommendation.EscalateOperations, ref passed); Check("compound has explicit factors", compound.Patterns.Count >= 7 && compound.Patterns.All(x => !string.IsNullOrWhiteSpace(x.Reason)), ref passed);

var missing = false; try { await service.EvaluateAsync(new("AFM-MISSING", "scenario")); } catch (KeyNotFoundException) { missing = true; } Check("missing merchant rejected", missing, ref passed);
var stored = await repository.GetLatestAsync("AFM-COMPOUND"); Check("finding persisted", stored?.FindingId == compound.FindingId, ref passed);
var events = await audit.GetAsync(compound.FindingId); Check("audit exists", events.Count == 1, ref passed); Check("merchant blocking absent", events.All(x => x.Metadata["automaticMerchantBlocking"] == "false"), ref passed); Check("merchant suspension absent", events.All(x => x.Metadata["automaticMerchantSuspension"] == "false"), ref passed); Check("settlement freeze absent", events.All(x => x.Metadata["automaticSettlementFreeze"] == "false"), ref passed); Check("payout freeze absent", events.All(x => x.Metadata["automaticPayoutFreeze"] == "false"), ref passed); Check("payment capture absent", events.All(x => x.Metadata["paymentCapturePerformed"] == "false"), ref passed); Check("money movement absent", events.All(x => x.Metadata["moneyMovementPerformed"] == "false"), ref passed); Check("ledger mutation absent", events.All(x => x.Metadata["ledgerMutationPerformed"] == "false"), ref passed);

Console.WriteLine($"\nChecks: {passed}\nPassed: {passed}\nFailed: 0\nSkipped: 0\n"); Console.WriteLine("All AFW-DLV-0019.6 merchant intelligence scenarios passed.\nMerchant risk scoring: IMPLEMENTED\nCommerce intelligence: IMPLEMENTED\nPattern detection: IMPLEMENTED\nExplainability: IMPLEMENTED\nProtection recommendations: IMPLEMENTED\nAutomatic merchant blocking: NOT IMPLEMENTED\nAutomatic merchant suspension: NOT IMPLEMENTED\nAutomatic settlement freeze: NOT IMPLEMENTED\nAutomatic payout freeze: NOT IMPLEMENTED\nPayment capture: NOT IMPLEMENTED\nMoney movement: NOT IMPLEMENTED\nLedger mutation: NOT IMPLEMENTED\nDecision: READY FOR REVIEW");
sealed class FixedClock(DateTimeOffset now) : IMerchantIntelligenceClock { public DateTimeOffset UtcNow { get; } = now; }
