using AfriWallet.Merchants.PaymentDecision.Application.Abstractions;using AfriWallet.Merchants.PaymentDecision.Application.Commands;using AfriWallet.Merchants.PaymentDecision.Application.Policies;using AfriWallet.Merchants.PaymentDecision.Application.Services;using AfriWallet.Merchants.PaymentDecision.Domain.Decisions;using AfriWallet.Merchants.PaymentDecision.Infrastructure;
static void Check(string n,bool ok,ref int p){Console.WriteLine($"{n,-56} {(ok?"PASS":"FAIL")}");if(!ok)throw new InvalidOperationException(n);p++;}
var p=0;var now=new DateTimeOffset(2027,4,5,9,0,0,TimeSpan.Zero);const string actor="scenario-runner";var reader=new SandboxPaymentIntentDecisionReader();var repo=new InMemoryMerchantPaymentDecisionRepository();var audit=new InMemoryMerchantPaymentDecisionAuditStore();var service=new MerchantPaymentDecisionService(repo,reader,audit,new FixedClock(now),new MerchantPaymentAuthorizationPolicy());
Guid Seed(string status="ReadyForAuthorization",int risk=20,long amount=1000,string registry="Active",string verification="Verified",string currency="XOF",string method="sandbox-card",DateTimeOffset? expires=null){var id=Guid.NewGuid();reader.Set(new PaymentIntentDecisionSnapshot(id,Guid.NewGuid(),"AFM-TEST",status,amount,currency,method,registry,verification,risk,expires??now.AddHours(1)));return id;}
var missing=false;try{await service.EvaluateAsync(new(Guid.NewGuid(),actor));}catch(KeyNotFoundException){missing=true;}Check("missing payment intent blocked",missing,ref p);
var lowId=Seed();var low=await service.EvaluateAsync(new(lowId,actor));Check("low risk authorizes",low.DecisionType==PaymentAuthorizationDecisionType.Authorize,ref p);Check("low risk approved",low.Status==PaymentAuthorizationDecisionStatus.Approved,ref p);Check("low risk reason",low.ReasonCode==PaymentDecisionReasonCode.LowRiskAuthorization,ref p);Check("policy version stamped",low.PolicyVersion=="AFW-MERCHANT-PAYMENT-AUTHORIZATION:1.0",ref p);Check("factors explain decision",low.FactorCount==5,ref p);
var same=await service.EvaluateAsync(new(lowId,actor));Check("evaluation is idempotent",same.DecisionId==low.DecisionId,ref p);
var step=await service.EvaluateAsync(new(Seed(risk:60),actor));Check("elevated risk requires step up",step.DecisionType==PaymentAuthorizationDecisionType.RequiresStepUp,ref p);Check("step up pending",step.Status==PaymentAuthorizationDecisionStatus.PendingStepUp,ref p);var afterStep=await service.CompleteStepUpAsync(new(step.DecisionId,actor));Check("step up completes authorization",afterStep.DecisionType==PaymentAuthorizationDecisionType.Authorize&&afterStep.Status==PaymentAuthorizationDecisionStatus.Approved,ref p);Check("step up reason recorded",afterStep.ReasonCode==PaymentDecisionReasonCode.StepUpSatisfied,ref p);var capture=await service.MarkCaptureEligibleAsync(new(step.DecisionId,actor));Check("approved authorization capture eligible",capture.DecisionType==PaymentAuthorizationDecisionType.CaptureEligible,ref p);Check("capture eligibility reason",capture.ReasonCode==PaymentDecisionReasonCode.CaptureEligibilityConfirmed,ref p);
var critical=await service.EvaluateAsync(new(Seed(risk:85),actor));Check("critical risk declines",critical.DecisionType==PaymentAuthorizationDecisionType.Decline,ref p);Check("critical risk declined status",critical.Status==PaymentAuthorizationDecisionStatus.Declined,ref p);var tooHigh=await service.EvaluateAsync(new(Seed(amount:1000001),actor));Check("amount outside policy declines",tooHigh.ReasonCode==PaymentDecisionReasonCode.AmountOutsidePolicy,ref p);var inactive=await service.EvaluateAsync(new(Seed(registry:"Suspended"),actor));Check("ineligible merchant declines",inactive.ReasonCode==PaymentDecisionReasonCode.MerchantNotEligible,ref p);var notReady=await service.EvaluateAsync(new(Seed(status:"RequiresPaymentMethod"),actor));Check("not ready intent declines",notReady.ReasonCode==PaymentDecisionReasonCode.PaymentIntentNotReady,ref p);var expired=await service.EvaluateAsync(new(Seed(expires:now),actor));Check("expired intent declines",expired.ReasonCode==PaymentDecisionReasonCode.PaymentIntentExpired,ref p);var badMethod=await service.EvaluateAsync(new(Seed(method:""),actor));Check("missing method declines",badMethod.ReasonCode==PaymentDecisionReasonCode.UnsupportedPaymentMethod,ref p);
var reevaluated=await service.ReevaluateAsync(new(lowId,"risk snapshot refreshed",actor));Check("reevaluation creates new decision",reevaluated.DecisionId!=low.DecisionId,ref p);var old=await service.GetAsync(low.DecisionId);Check("prior decision superseded",old.Status==PaymentAuthorizationDecisionStatus.Superseded,ref p);var active=await repo.GetActiveByPaymentIntentAsync(lowId);Check("reevaluation active decision preserved",active?.DecisionId==reevaluated.DecisionId,ref p);
var invalidCapture=false;try{await service.MarkCaptureEligibleAsync(new(critical.DecisionId,actor));}catch(InvalidOperationException){invalidCapture=true;}Check("declined decision not capture eligible",invalidCapture,ref p);var invalidStep=false;try{await service.CompleteStepUpAsync(new(low.DecisionId,actor));}catch(InvalidOperationException){invalidStep=true;}Check("non step-up cannot complete step-up",invalidStep,ref p);var events=await audit.GetAsync(step.DecisionId);Check("audit exists",events.Count>=3,ref p);Check("authorization execution absent",events.All(x=>x.Metadata["authorizationExecutionPerformed"]=="false"),ref p);Check("capture execution absent",events.All(x=>x.Metadata["captureExecutionPerformed"]=="false"),ref p);Check("settlement absent",events.All(x=>x.Metadata["settlementPerformed"]=="false"),ref p);Check("payout absent",events.All(x=>x.Metadata["payoutPerformed"]=="false"),ref p);Check("money movement absent",events.All(x=>x.Metadata["moneyMovementPerformed"]=="false"),ref p);Check("ledger mutation absent",events.All(x=>x.Metadata["ledgerMutationPerformed"]=="false"),ref p);
Console.WriteLine($"\nChecks: {p}\nPassed: {p}\nFailed: 0\nSkipped: 0\n");Console.WriteLine("All AFW-DLV-0019.4 merchant payment decision scenarios passed.\nAuthorization decision: IMPLEMENTED\nStep-up decision: IMPLEMENTED\nCapture eligibility decision: IMPLEMENTED\nAuthorization execution: NOT IMPLEMENTED\nCapture execution: NOT IMPLEMENTED\nSettlement: NOT IMPLEMENTED\nPayout: NOT IMPLEMENTED\nMoney movement: NOT IMPLEMENTED\nLedger mutation: NOT IMPLEMENTED\nDecision: READY FOR REVIEW");sealed class FixedClock(DateTimeOffset n):IMerchantPaymentDecisionClock{public DateTimeOffset UtcNow{get;}=n;}
