using AfriWallet.Banking.Domain.Entities;

namespace AfriWallet.Banking.Infrastructure;

internal static class SeedData
{
    public static List<BankProvider> CreateSeedProviders() =>
    [
        new BankProvider
        {
            ProviderId = "bank-sepa-sandbox",
            ProviderCode = "sepa-sandbox",
            DisplayName = "DE SEPA Sandbox",
            LegalName = "Deutsche Bank Sandbox GmbH",
            CountryCode = "DE",
            CurrencyCode = "EUR",
            SupportedCurrencies = new[] { "EUR", "USD" },
            SwiftCode = "DEUTDEFF",
            Bic = "DEUTDEFF",
            NationalClearingCode = "50010517",
            TransferSchemes = new[] { "SEPA", "INSTANT" },
            SupportsSepa = true,
            SupportsSwift = false,
            SupportsInstantPayments = true,
            SupportsDomesticTransfers = false,
            SettlementWindow = "T+1",
            CutoffTime = "17:00 UTC",
            EstimatedDelivery = "1 business day",
            EstimatedDeliveryDays = 1,
            MinimumAmountMinor = 1_000m,
            MaximumAmountMinor = 250_000_000m,
            FixedFeeMinor = 150m,
            PercentageFee = 0.0025m,
            Environment = "Sandbox",
            Status = "Active",
            Priority = 100,
            Capabilities = new[] { "SEPA", "Instant", "BICValidation" }
        },
        new BankProvider
        {
            ProviderId = "bank-swift-global",
            ProviderCode = "swift-global",
            DisplayName = "Global SWIFT",
            LegalName = "Global Clearing Network Ltd",
            CountryCode = "GB",
            CurrencyCode = "USD",
            SupportedCurrencies = new[] { "USD", "EUR", "GBP" },
            SwiftCode = "CHASUS33",
            Bic = "CHASUS33",
            NationalClearingCode = "SWIFT-GB",
            TransferSchemes = new[] { "SWIFT" },
            SupportsSepa = false,
            SupportsSwift = true,
            SupportsInstantPayments = false,
            SupportsDomesticTransfers = false,
            SettlementWindow = "T+2",
            CutoffTime = "16:00 UTC",
            EstimatedDelivery = "2 business days",
            EstimatedDeliveryDays = 2,
            MinimumAmountMinor = 10_000m,
            MaximumAmountMinor = 500_000_000m,
            FixedFeeMinor = 350m,
            PercentageFee = 0.0035m,
            Environment = "Sandbox",
            Status = "Active",
            Priority = 90,
            Capabilities = new[] { "SWIFT", "BICValidation" }
        },
        new BankProvider
        {
            ProviderId = "bank-cm-demo",
            ProviderCode = "cm-demo",
            DisplayName = "Cameroon Demo Bank",
            LegalName = "Cameroon National Transfer Bank",
            CountryCode = "CM",
            CurrencyCode = "XAF",
            SupportedCurrencies = new[] { "XAF" },
            SwiftCode = null,
            Bic = null,
            NationalClearingCode = "CM001",
            TransferSchemes = new[] { "DOMESTIC", "INSTANT" },
            SupportsSepa = false,
            SupportsSwift = false,
            SupportsInstantPayments = true,
            SupportsDomesticTransfers = true,
            SettlementWindow = "Instant",
            CutoffTime = "15:00 WAT",
            EstimatedDelivery = "under 30 minutes",
            EstimatedDeliveryDays = 0,
            MinimumAmountMinor = 500m,
            MaximumAmountMinor = 50_000_000m,
            FixedFeeMinor = 75m,
            PercentageFee = 0.001m,
            Environment = "Sandbox",
            Status = "Active",
            Priority = 80,
            Capabilities = new[] { "Domestic", "Instant" }
        },
        new BankProvider
        {
            ProviderId = "bank-ke-demo",
            ProviderCode = "ke-demo",
            DisplayName = "Kenya Demo Bank",
            LegalName = "Kenyatta Clearing Services",
            CountryCode = "KE",
            CurrencyCode = "KES",
            SupportedCurrencies = new[] { "KES" },
            SwiftCode = null,
            Bic = null,
            NationalClearingCode = "KE001",
            TransferSchemes = new[] { "DOMESTIC", "INSTANT" },
            SupportsSepa = false,
            SupportsSwift = false,
            SupportsInstantPayments = true,
            SupportsDomesticTransfers = true,
            SettlementWindow = "Instant",
            CutoffTime = "14:00 EAT",
            EstimatedDelivery = "under 15 minutes",
            EstimatedDeliveryDays = 0,
            MinimumAmountMinor = 100m,
            MaximumAmountMinor = 25_000_000m,
            FixedFeeMinor = 50m,
            PercentageFee = 0.0015m,
            Environment = "Sandbox",
            Status = "Active",
            Priority = 70,
            Capabilities = new[] { "Domestic", "Instant" }
        },
        new BankProvider
        {
            ProviderId = "bank-ng-demo",
            ProviderCode = "ng-demo",
            DisplayName = "Nigeria Demo Bank",
            LegalName = "Nigerian Settlement Cooperative",
            CountryCode = "NG",
            CurrencyCode = "NGN",
            SupportedCurrencies = new[] { "NGN" },
            SwiftCode = null,
            Bic = null,
            NationalClearingCode = "NG001",
            TransferSchemes = new[] { "DOMESTIC" },
            SupportsSepa = false,
            SupportsSwift = false,
            SupportsInstantPayments = false,
            SupportsDomesticTransfers = true,
            SettlementWindow = "T+1",
            CutoffTime = "12:00 WAT",
            EstimatedDelivery = "1 business day",
            EstimatedDeliveryDays = 1,
            MinimumAmountMinor = 200m,
            MaximumAmountMinor = 10_000_000m,
            FixedFeeMinor = 100m,
            PercentageFee = 0.002m,
            Environment = "Sandbox",
            Status = "Inactive",
            Priority = 60,
            MaintenanceMode = true,
            Capabilities = new[] { "Domestic" }
        }
    ];
}
