using AfriWallet.Merchants.Checkout.Application.Abstractions;
using AfriWallet.Merchants.Checkout.Application.Commands;
using AfriWallet.Merchants.Checkout.Application.Policies;
using AfriWallet.Merchants.Checkout.Application.Services;
using AfriWallet.Merchants.Checkout.Domain.Checkout;
using AfriWallet.Merchants.Checkout.Domain.PaymentIntents;
using AfriWallet.Merchants.Checkout.Infrastructure;

static void Check(string name, bool ok, ref int passed) { Console.WriteLine($"{name,-58} {(ok ? "PASS" : "FAIL")}"); if (!ok) throw new InvalidOperationException(name); passed++; }
var passed = 0; var now = new DateTimeOffset(2027, 3, 4, 9, 0, 0, TimeSpan.Zero); const string actor = "scenario-runner";
var merchants = new SandboxMerchantCommerceEligibilityReader(); var sessions = new InMemoryCheckoutSessionRepository(); var intents = new InMemoryPaymentIntentRepository(); var audit = new InMemoryCheckoutAuditStore(); var service = new CheckoutService(sessions, intents, merchants, audit, new FixedClock(now), new CheckoutEligibilityPolicy());
CreateCheckoutSessionCommand Cmd(string merchant, string key, string? order = null, int expiry = 30) => new(merchant, "customer-1", order, 12345, "XOF", "https://merchant.test/return", new Dictionary<string,string> { ["cart"] = "42" }, expiry, key, actor);
merchants.Set(new MerchantCommerceEligibilitySnapshot("AFM-INACTIVE", "Registered", "Verified", "CI", "XOF"));
var inactiveBlocked = false; try { await service.CreateAsync(Cmd("AFM-INACTIVE", "key-inactive")); } catch (InvalidOperationException) { inactiveBlocked = true; } Check("inactive merchant blocked", inactiveBlocked, ref passed);
merchants.Set(new MerchantCommerceEligibilitySnapshot("AFM-UNVERIFIED", "Active", "PendingVerification", "CI", "XOF"));
var unverifiedBlocked = false; try { await service.CreateAsync(Cmd("AFM-UNVERIFIED", "key-unverified")); } catch (InvalidOperationException) { unverifiedBlocked = true; } Check("unverified merchant blocked", unverifiedBlocked, ref passed);
var missingBlocked = false; try { await service.CreateAsync(Cmd("AFM-MISSING", "key-missing")); } catch (KeyNotFoundException) { missingBlocked = true; } Check("missing merchant blocked", missingBlocked, ref passed);
merchants.Set(new MerchantCommerceEligibilitySnapshot("AFM-ELIGIBLE", "Active", "Verified", "CI", "XOF"));
var created = await service.CreateAsync(Cmd("AFM-ELIGIBLE", "key-1", "order-1")); Check("checkout created open", created.Status == CheckoutSessionStatus.Open, ref passed); Check("payment intent attached", created.PaymentIntentId != Guid.Empty, ref passed); Check("currency preserved", created.Currency == "XOF", ref passed);
var intent = await service.GetPaymentIntentAsync(created.PaymentIntentId); Check("intent requires payment method", intent.Status == PaymentIntentStatus.RequiresPaymentMethod, ref passed);
var repeated = await service.CreateAsync(Cmd("AFM-ELIGIBLE", "key-1", "order-different")); Check("idempotency returns same checkout", repeated.CheckoutSessionId == created.CheckoutSessionId, ref passed);
var orderRepeat = await service.CreateAsync(Cmd("AFM-ELIGIBLE", "key-2", "order-1")); Check("order reference prevents duplicate checkout", orderRepeat.CheckoutSessionId == created.CheckoutSessionId, ref passed);
var ready = await service.AttachPaymentMethodAsync(new AttachCheckoutPaymentMethodCommand(created.CheckoutSessionId, "sandbox-card", "tok_sandbox_1", actor)); Check("payment method makes checkout ready", ready.Status == CheckoutSessionStatus.ReadyForPayment, ref passed);
var readyIntent = await service.GetPaymentIntentAsync(created.PaymentIntentId); Check("intent ready for authorization only", readyIntent.Status == PaymentIntentStatus.ReadyForAuthorization, ref passed); Check("token reference type stored", readyIntent.PaymentMethodType == "sandbox-card", ref passed);
var attachAgainBlocked = false; try { await service.AttachPaymentMethodAsync(new AttachCheckoutPaymentMethodCommand(created.CheckoutSessionId, "sandbox-card", "tok-2", actor)); } catch (InvalidOperationException) { attachAgainBlocked = true; } Check("second payment method blocked", attachAgainBlocked, ref passed);
var second = await service.CreateAsync(Cmd("AFM-ELIGIBLE", "key-3", "order-3")); var cancelled = await service.CancelAsync(new CancelCheckoutSessionCommand(second.CheckoutSessionId, actor)); Check("checkout cancelled", cancelled.Status == CheckoutSessionStatus.Cancelled, ref passed); var cancelledIntent = await service.GetPaymentIntentAsync(cancelled.PaymentIntentId); Check("intent cancelled with checkout", cancelledIntent.Status == PaymentIntentStatus.Cancelled, ref passed);
var mutateCancelledBlocked = false; try { await service.AttachPaymentMethodAsync(new AttachCheckoutPaymentMethodCommand(second.CheckoutSessionId, "x", "tok", actor)); } catch (InvalidOperationException) { mutateCancelledBlocked = true; } Check("cancelled checkout immutable", mutateCancelledBlocked, ref passed);
var third = await service.CreateAsync(Cmd("AFM-ELIGIBLE", "key-4", "order-4")); var expired = await service.ExpireAsync(new ExpireCheckoutSessionCommand(third.CheckoutSessionId, actor)); Check("checkout expired", expired.Status == CheckoutSessionStatus.Expired, ref passed); var expiredIntent = await service.GetPaymentIntentAsync(expired.PaymentIntentId); Check("intent expired with checkout", expiredIntent.Status == PaymentIntentStatus.Expired, ref passed);
var expireAgainBlocked = false; try { await service.ExpireAsync(new ExpireCheckoutSessionCommand(third.CheckoutSessionId, actor)); } catch (InvalidOperationException) { expireAgainBlocked = true; } Check("expired checkout immutable", expireAgainBlocked, ref passed);
var invalidAmountBlocked = false; try { await service.CreateAsync(new CreateCheckoutSessionCommand("AFM-ELIGIBLE", null, null, 0, "XOF", "https://return", null, 30, "key-bad", actor)); } catch (ArgumentOutOfRangeException) { invalidAmountBlocked = true; } Check("nonpositive amount blocked", invalidAmountBlocked, ref passed);
var invalidExpiryBlocked = false; try { await service.CreateAsync(Cmd("AFM-ELIGIBLE", "key-expiry", expiry: 0)); } catch (ArgumentOutOfRangeException) { invalidExpiryBlocked = true; } Check("invalid expiry blocked", invalidExpiryBlocked, ref passed);
var metadataTooLargeBlocked = false; try { await service.CreateAsync(new CreateCheckoutSessionCommand("AFM-ELIGIBLE", null, null, 1, "XOF", "https://return", Enumerable.Range(0, 21).ToDictionary(x => x.ToString(), x => "v"), 30, "key-meta", actor)); } catch (ArgumentException) { metadataTooLargeBlocked = true; } Check("oversized metadata blocked", metadataTooLargeBlocked, ref passed);
var missingSessionBlocked = false; try { await service.GetSessionAsync(Guid.NewGuid()); } catch (KeyNotFoundException) { missingSessionBlocked = true; } Check("missing session blocked", missingSessionBlocked, ref passed);
var events = await audit.GetAsync(created.CheckoutSessionId); Check("audit exists", events.Count >= 2, ref passed); Check("authorization absent", events.All(x => x.Metadata["authorizationPerformed"] == "false"), ref passed); Check("capture absent", events.All(x => x.Metadata["capturePerformed"] == "false"), ref passed); Check("settlement absent", events.All(x => x.Metadata["settlementPerformed"] == "false"), ref passed); Check("payout absent", events.All(x => x.Metadata["payoutPerformed"] == "false"), ref passed); Check("money movement absent", events.All(x => x.Metadata["moneyMovementPerformed"] == "false"), ref passed); Check("ledger mutation absent", events.All(x => x.Metadata["ledgerMutationPerformed"] == "false"), ref passed);
Console.WriteLine($"\nChecks: {passed}\nPassed: {passed}\nFailed: 0\nSkipped: 0\n"); Console.WriteLine("All AFW-DLV-0019.3 merchant checkout scenarios passed."); Console.WriteLine("Checkout Session: IMPLEMENTED\nPayment Intent: IMPLEMENTED\nPayment method reference: IMPLEMENTED\nAuthorization: NOT IMPLEMENTED\nCapture: NOT IMPLEMENTED\nSettlement: NOT IMPLEMENTED\nPayout: NOT IMPLEMENTED\nMoney movement: NOT IMPLEMENTED\nLedger mutation: NOT IMPLEMENTED\nDecision: READY FOR REVIEW");
sealed class FixedClock(DateTimeOffset now) : ICheckoutClock { public DateTimeOffset UtcNow { get; } = now; }
