using AfriWallet.Fraud.DeviceRisk.Application.Abstractions;using AfriWallet.Fraud.DeviceRisk.Application.Policies;using AfriWallet.Fraud.DeviceRisk.Application.Services;using AfriWallet.Fraud.DeviceRisk.Domain.Models;using AfriWallet.Fraud.DeviceRisk.Domain.Signals;using AfriWallet.Fraud.DeviceRisk.Infrastructure;
static void Check(string n,bool ok,ref int p){Console.WriteLine($"{n,-45} {(ok?"PASS":"FAIL")}");if(!ok)throw new InvalidOperationException(n);p++;}static FraudSignalSnapshot S(string id,string type,string st,string sid,DateTimeOffset at,Dictionary<string,string>? a=null)=>new(id,type,st,sid,"Medium",at,a??new());
var p=0;var now=new DateTimeOffset(2026,8,16,20,0,0,TimeSpan.Zero);var reader=new SandboxFraudSignalReader();var repo=new InMemoryDeviceRiskRepository();var audit=new InMemoryDeviceRiskAuditStore();var service=new DeviceAccountRiskService(reader,repo,audit,new FixedClock(now),new DeviceRiskPolicy());var baseline=await service.CalculateAsync(new("AWID-BASE","DEV-BASE","runner"));Check("baseline risk profile created",baseline.RiskProfileId!=Guid.Empty,ref p);Check("baseline score low",baseline.Band==RiskBand.Low,ref p);Check("baseline recommendation allow",baseline.Recommendation==RiskRecommendation.Allow,ref p);
reader.Add(S("new-1","NewDevice","DEVICE","DEV-NEW",now));var nr=await service.CalculateAsync(new("AWID-NEW","DEV-NEW","runner"));Check("new device factor detected",nr.Factors.Any(x=>x.Type==DeviceRiskFactorType.NewDevice),ref p);Check("new device risk elevated",nr.Score==20,ref p);
for(var i=0;i<5;i++)reader.Add(S($"login-{i}","LoginFailed","AWID","AWID-LOGIN",now.AddMinutes(i),new(){{"deviceId","OTHER"}}));var lr=await service.CalculateAsync(new("AWID-LOGIN","DEV-LOGIN","runner"));Check("login failure factor detected",lr.Factors.Any(x=>x.Type==DeviceRiskFactorType.LoginFailures),ref p);Check("login velocity factor detected",lr.Factors.Any(x=>x.Type==DeviceRiskFactorType.LoginVelocity),ref p);Check("login risk high or critical",lr.Band is RiskBand.High or RiskBand.Critical,ref p);
for(var i=0;i<3;i++)reader.Add(S($"multi-{i}","LoginFailed","AWID","AWID-MULTI",now,new(){{"deviceId",$"DEV-{i}"}}));var mr=await service.CalculateAsync(new("AWID-MULTI","DEV-0","runner"));Check("multiple device factor detected",mr.Factors.Any(x=>x.Type==DeviceRiskFactorType.MultipleDevices),ref p);
reader.Add(S("session-1","LoginFailed","DEVICE","DEV-SESSION",now,new(){{"sessionAnomaly","true"}}));var sr=await service.CalculateAsync(new("AWID-SESSION","DEV-SESSION","runner"));Check("session anomaly detected",sr.Factors.Any(x=>x.Type==DeviceRiskFactorType.SessionAnomaly),ref p);
reader.Add(S("changed-1","DeviceChanged","DEVICE","DEV-CHANGED",now));var cr=await service.CalculateAsync(new("AWID-CHANGED","DEV-CHANGED","runner"));Check("device changed detected",cr.Factors.Any(x=>x.Type==DeviceRiskFactorType.DeviceChanged),ref p);
var stored=await repo.GetLatestAsync(lr.Awid,lr.DeviceId);Check("risk profile persisted",stored?.ProfileId==lr.RiskProfileId,ref p);Check("risk audit recorded",(await audit.GetByProfileAsync(lr.RiskProfileId)).Count==1,ref p);Check("recommendation remains non-executing",Enum.IsDefined(lr.Recommendation),ref p);Console.WriteLine($"\nChecks: {p}\nPassed: {p}\nFailed: 0\nSkipped: 0\n");Console.WriteLine("All AFW-DLV-0017.2 device and account risk scenarios passed.\nAutomatic payment blocking: NOT IMPLEMENTED\nAutomatic account suspension: NOT IMPLEMENTED\nDecision: READY FOR REVIEW");
sealed class FixedClock(DateTimeOffset now):IDeviceRiskClock{public DateTimeOffset UtcNow{get;}=now;}