<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Webhooks/PartnerWebhooks.Application/PartnerWebhooks.Application.csproj" />
    <ProjectReference Include="../../src/Webhooks/PartnerWebhooks.Infrastructure/PartnerWebhooks.Infrastructure.csproj" />
  </ItemGroup>
</Project>
