<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FraudInvestigation.Application\FraudInvestigation.Application.csproj" />
    <ProjectReference Include="..\FraudInvestigation.Infrastructure\FraudInvestigation.Infrastructure.csproj" />
  </ItemGroup>
</Project>