<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Banking\Banking.Application\Banking.Application.csproj" />
    <ProjectReference Include="..\..\src\Banking\Banking.Infrastructure\Banking.Infrastructure.csproj" />
  </ItemGroup>
</Project>
