<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MerchantSettlement.Domain\MerchantSettlement.Domain.csproj"/>
    <ProjectReference Include="..\MerchantSettlement.Application\MerchantSettlement.Application.csproj"/>
    <ProjectReference Include="..\..\..\FinancialPlatform\Settlement\Settlement.Application\Settlement.Application.csproj"/>
    <ProjectReference Include="..\..\..\FinancialPlatform\Settlement\Settlement.Domain\Settlement.Domain.csproj"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>
</Project>
