<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Settlement.Domain\Settlement.Domain.csproj" />
    <ProjectReference Include="..\Settlement.Application\Settlement.Application.csproj" />
    <ProjectReference Include="..\..\..\Ledger\Ledger.Application\Ledger.Application.csproj" />
    <ProjectReference Include="..\..\..\Ledger\Ledger.Domain\Ledger.Domain.csproj" />
    <ProjectReference Include="..\..\..\Balance\Balance.Application\Balance.Application.csproj" />
    <ProjectReference Include="..\..\..\Balance\Balance.Domain\Balance.Domain.csproj" />
    <ProjectReference Include="..\..\..\Fx\Fx.Application\Fx.Application.csproj" />
    <ProjectReference Include="..\..\..\Fx\Fx.Domain\Fx.Domain.csproj" />
    <ProjectReference Include="..\..\Treasury\Treasury.Application\Treasury.Application.csproj" />
    <ProjectReference Include="..\..\Treasury\Treasury.Domain\Treasury.Domain.csproj" />
    <ProjectReference Include="..\..\Treasury\Treasury.Infrastructure\Treasury.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
