<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/P2P/P2P.Infrastructure/P2P.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Wallet/Wallet.Application/Wallet.Application.csproj" />
    <ProjectReference Include="../../src/Wallet/Wallet.Domain/Wallet.Domain.csproj" />
  </ItemGroup>
</Project>
