<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Merchants\MerchantReceivables\MerchantReceivables.Domain\MerchantReceivables.Domain.csproj" />
    <ProjectReference Include="..\..\src\Merchants\MerchantReceivables\MerchantReceivables.Application\MerchantReceivables.Application.csproj" />
    <ProjectReference Include="..\..\src\Merchants\MerchantReceivables\MerchantReceivables.Infrastructure\MerchantReceivables.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>
</Project>
